// ============================================================
// NOCTURNE — train-voice.js
// Plays pre-generated ElevenLabs voice lines for train NPCs.
// Hooks into _askQuestion() and accusation responses.
// Lip sync driven by actual audio duration, not word count.
// KB v10 · Nocturne Studios LLC · MMXXVI
// ============================================================

'use strict';

// ── VOICE FILE MAP ────────────────────────────────────────
// Maps charId + questionId → audio filename
// Matches files generated by generate-ph-voices.js
//                       and generate-train-voices.js

const TRAIN_VOICE_MAP = {

  'elliot': {
    'E1':            'nocturne-voice-elliot-e1.mp3',
    'E2':            'nocturne-voice-elliot-e2.mp3',
    'E3':            'nocturne-voice-elliot-e3.mp3',
    'E4':            'nocturne-voice-elliot-e4.mp3',
    'E5':            'nocturne-voice-elliot-e5.mp3',
    'E6':            'nocturne-voice-elliot-e6.mp3',
    'SNAP':          'nocturne-voice-elliot-snap.mp3',
    'ACCUSE_WRONG':  'nocturne-voice-elliot-accuse-wrong.mp3',
  },

  'marcus': {
    'M1':            'nocturne-voice-marcus-m1.mp3',
    'M2':            'nocturne-voice-marcus-m2.mp3',
    'M3':            'nocturne-voice-marcus-m3.mp3',
    'M4':            'nocturne-voice-marcus-m4.mp3',
    'M5':            'nocturne-voice-marcus-m5.mp3',
    'M6':            'nocturne-voice-marcus-m6.mp3',
    'SNAP':          'nocturne-voice-marcus-snap.mp3',
    'ACCUSE_WRONG':  'nocturne-voice-marcus-accuse-wrong.mp3',
  },

  'todd': {
    'P1':            'nocturne-voice-ph-train-p1.mp3',
    'P2':            'nocturne-voice-ph-train-p2.mp3',
    'P3':            'nocturne-voice-ph-train-p3.mp3',
    'P4':            'nocturne-voice-ph-train-p4.mp3',
    'P5':            'nocturne-voice-ph-train-p5.mp3',
    'P6':            'nocturne-voice-ph-train-p6.mp3',
    'SNAP':          'nocturne-voice-ph-train-snap.mp3',
    'ACCUSE_CORRECT':'nocturne-voice-ph-train-accuse-correct.mp3',
  },

};

// ── AUDIO STATE ───────────────────────────────────────────
let _audioCtx      = null;
let _activeSource  = null;
let _activeChar    = null;
let _lipSyncTimer  = null;
let _activeFetch   = null;
let _requestId     = 0;
let _activeRaf     = null; // requestAnimationFrame handle for lip sync

// ── AUDIO CONTEXT ─────────────────────────────────────────
// Reuses NocturneSound's context if available, otherwise own
function _getCtx() {
  if (_audioCtx) return _audioCtx;
  try {
    _audioCtx = new (window.AudioContext || window.webkitAudioContext)();
  } catch(e) { return null; }
  return _audioCtx;
}

function _resume() {
  const ctx = _getCtx();
  if (ctx && ctx.state === 'suspended') ctx.resume();
}

// ── STOP ANY PLAYING VOICE ────────────────────────────────
function _stopActive() {
  // Abort any in-flight fetch
  if (_activeFetch) {
    _activeFetch.abort();
    _activeFetch = null;
  }
  // Stop playing audio
  if (_activeSource) {
    try { _activeSource.stop(); } catch(e) {}
    _activeSource = null;
  }
  if (_lipSyncTimer) {
    clearTimeout(_lipSyncTimer);
    _lipSyncTimer = null;
  }
  // Remove speaking class from all train cards
  if (_activeChar) {
    const card = document.getElementById(`train-card-${_activeChar}`);
    if (card) card.classList.remove('speaking');
    _activeChar = null;
  }
}

// ── PLAY VOICE LINE ───────────────────────────────────────
async function playTrainVoice(charId, lineId) {
  const map      = TRAIN_VOICE_MAP[charId];
  if (!map) return;
  const filename = map[lineId];
  if (!filename) return;

  // Stop anything currently playing or fetching
  _stopActive();
  _resume();

  const ctx = _getCtx();
  if (!ctx) return;

  // Tag this request — if a newer one starts before fetch finishes, discard this one
  const myId = ++_requestId;
  const controller = new AbortController();
  _activeFetch = controller;

  // Try subpath first (dev server), then root (production)
  const urls = [
    `/nocturne-midnight-estate/audio/${filename}`,
    `/audio/${filename}`,
  ];

  let buffer;
  let loaded = false;
  for (const url of urls) {
    try {
      const controller2 = new AbortController();
      _activeFetch = controller2;
      const response = await fetch(url, { signal: controller2.signal });
      if (!response.ok) continue;
      const arrayBuffer = await response.arrayBuffer();
      if (myId !== _requestId) return;
      buffer = await ctx.decodeAudioData(arrayBuffer);
      loaded = true;
      break;
    } catch(e) {
      if (e.name === 'AbortError') return;
      // try next URL
    }
  }
  if (!loaded || !buffer) return;
  _activeFetch = null;

  const source   = ctx.createBufferSource();
  const gainNode = ctx.createGain();
  const analyser = ctx.createAnalyser();
  analyser.fftSize = 256;
  analyser.smoothingTimeConstant = 0.4;

  source.buffer  = buffer;
  gainNode.gain.value = 0.9;
  source.connect(gainNode);
  gainNode.connect(analyser);
  analyser.connect(ctx.destination);

  _activeSource = source;
  _activeChar   = charId;

  const card  = document.getElementById(`train-card-${charId}`);
  const mouth = card ? card.querySelector('.mouth-overlay') : null;
  if (card) card.classList.add('speaking');

  // Real-time lip sync — driven by audio volume
  const dataArray = new Uint8Array(analyser.frequencyBinCount);
  let _rafId = null;

  function _animateMouth() {
    if (!_activeSource) return;
    analyser.getByteFrequencyData(dataArray);

    // Speech frequency range (bins 2-18 covers ~300-3000Hz)
    let sum = 0;
    for (let i = 2; i < 18; i++) sum += dataArray[i];
    const avg = sum / 16;

    // Boost sensitivity
    const boosted = Math.min(255, avg * 3.0);

    // Map to height — max is proportional to character's mouth width
    const baseW = mouth ? parseFloat(getComputedStyle(mouth).width) || 20 : 20;
    const maxH  = Math.max(8, baseW * 0.45);
    const h     = 1 + (boosted / 255) * maxH;
    const isOpen = boosted > 15;

    if (mouth) {
      mouth.style.height       = h + 'px';
      mouth.style.background   = isOpen ? `rgba(60,25,25,${0.55 + (boosted/255)*0.35})` : 'transparent';
      mouth.style.borderRadius = isOpen
        ? `${38 + (1 - boosted/255)*8}% ${38 + (1 - boosted/255)*8}% ${55}% ${55}%`
        : '50%';
    }

    _rafId = requestAnimationFrame(_animateMouth);
  }

  _animateMouth();

  const durationMs = buffer.duration * 1000;
  _lipSyncTimer = setTimeout(() => {
    cancelAnimationFrame(_rafId);
    if (mouth) { mouth.style.height = ''; mouth.style.background = 'transparent'; mouth.style.borderRadius = '50%'; }
    if (card) card.classList.remove('speaking');
    _activeSource = null;
    _activeChar   = null;
    _lipSyncTimer = null;
  }, durationMs);

  source.onended = () => {
    cancelAnimationFrame(_rafId);
    if (mouth) { mouth.style.height = ''; mouth.style.background = 'transparent'; mouth.style.borderRadius = '50%'; }
    if (card) card.classList.remove('speaking');
    _activeSource = null;
    _activeChar   = null;
  };

  source.start(0);
}

// ── PLAY ACCUSATION VOICE ─────────────────────────────────
async function playTrainAccuseVoice(charId, outcome) {
  // outcome: 'correct' | 'wrong'
  const lineId = outcome === 'correct' ? 'ACCUSE_CORRECT' : 'ACCUSE_WRONG';
  await playTrainVoice(charId, lineId);
}

// ── PLAY SNAP ─────────────────────────────────────────────
async function playTrainSnapVoice(charId) {
  await playTrainVoice(charId, 'SNAP');
}

// ── PATCH _askQuestion ────────────────────────────────────
// Intercepts the existing function and adds voice playback.
// Does NOT replace the visual rendering — text still renders.
// The lip sync class is now driven by audio duration, so we
// also neutralise the word-count setTimeout in the original.

(function patchAskQuestion() {
  // Wait for train.js to define _askQuestion
  // It's a local function so we patch via module-level override
  // by wrapping the exported startTrainSequence hook.
  // We override _renderQuestions to intercept question clicks.

  const _originalStart = window.startTrainSequence;

  window.startTrainSequence = function() {
    _originalStart();
    _patchQuestionClicks();
  };

  // Also patch on car change — re-render rebuilds DOM
  const _originalRenderCar = window._renderCar;
  // _renderCar is local — we hook via MutationObserver instead

  const observer = new MutationObserver(() => {
    _patchQuestionClicks();
  });

  // Observe the questions list for DOM changes
  document.addEventListener('DOMContentLoaded', () => {
    const questionsList = document.getElementById('train-questions');
    if (questionsList) {
      observer.observe(questionsList, { childList: true, subtree: true });
    }

    // Also observe portrait zone for card rebuilds
    const portraitZone = document.getElementById('train-portrait-zone');
    if (portraitZone) {
      observer.observe(portraitZone, { childList: true });
    }
  });
})();

// ── PATCH QUESTION CLICKS ─────────────────────────────────
// Wraps each question item's onclick to fire voice BEFORE
// the original handler runs.

function _patchQuestionClicks() {
  const items = document.querySelectorAll('.train-question-item');
  items.forEach(item => {
    if (item.dataset.voicePatchd) return; // already patched
    item.dataset.voicePatchd = 'true';

    const originalOnclick = item.onclick;

    item.onclick = function(e) {
      // Extract charId and qId from the original closure
      // The original onclick is: () => _askQuestion(charId, q.id)
      // We need to fire voice — but we don't have the closure vars.
      // Solution: read from the active char state and the item text.
      const activeChar = _getActiveCharFromUI();
      const qId        = item.dataset.qid || _getQidFromItem(item);

      if (activeChar && qId) {
        playTrainVoice(activeChar, qId);
      }

      // Run original
      if (originalOnclick) originalOnclick.call(this, e);
    };
  });
}

// ── HELPERS ───────────────────────────────────────────────

function _getActiveCharFromUI() {
  // Find which card has the 'active' class
  const activeCard = document.querySelector('.train-npc-card.active');
  if (!activeCard) {
    // Single-char car — only one card, no active class needed
    const anyCard = document.querySelector('.train-npc-card');
    if (anyCard) return anyCard.id.replace('train-card-', '');
    return null;
  }
  return activeCard.id.replace('train-card-', '');
}

function _getQidFromItem(item) {
  // Question items don't store qId in the DOM by default.
  // We need train.js to stamp it — see note below.
  // Fallback: match text against known questions.
  return item.dataset.qid || null;
}

// ── STAMP QID ON QUESTION ITEMS ───────────────────────────
// train.js builds question items without a data-qid attribute.
// We patch _renderQuestions output by observing DOM insertion
// and stamping the qid based on onclick closure inspection.
// Cleaner solution: train.js updated to add data-qid (see below).
//
// For now: intercept at the NocturneEngine event level.

NocturneEngine.on('trainQuestionAsked', ({ charId, qId }) => {
  playTrainVoice(charId, qId);
});

NocturneEngine.on('trainSnapFired', ({ charId }) => {
  playTrainSnapVoice(charId);
});

NocturneEngine.on('trainAccusationMade', ({ charId, outcome }) => {
  playTrainAccuseVoice(charId, outcome);
});

// ── EXPOSE ────────────────────────────────────────────────
window.playTrainVoice       = playTrainVoice;
window.playTrainAccuseVoice = playTrainAccuseVoice;
window.playTrainSnapVoice   = playTrainSnapVoice;
window.stopTrainVoice       = _stopActive;
